FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY . ./

RUN cd modules/SampleModule && dotnet restore

RUN cd modules/SampleModule && dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime
WORKDIR /app
COPY --from=build-env /app/modules/SampleModule/out ./
ENTRYPOINT ["dotnet", "SampleModule.dll"]